MODSOURCE-722: relation "marc_records_tracking" does not exist
The Poppy version of MarcIndexersVersionDeletionVerticle fails when trying to delete for tenants that are still on Orchid.

```
2023-11-21 12:14:16.453 [vert.x-worker-thread-6] [] [] [] [] ERROR RecordDaoImpl        Something happened while deleting old marc_indexers versions tenantId=ubilm
io.vertx.pgclient.PgException: ERROR: relation "marc_records_tracking" does not exist (42P01)
```

The failure prevents running the deleteMarcIndexersOldVersions of the Poppy tenants.